name: Trivy Sbom
description: 'Trivy Sbom'

inputs:  
  TOKEN_SEC:
    description: 'Token secrets Sec'
    required: true

runs:
  using: composite
  steps:

  - name: Checkout
    uses: actions/checkout@v3

  - name: Trivy Sbom
    uses: aquasecurity/trivy-action@master
    with:
      scan-type: 'fs'
      format: 'github'
      output: 'dependency-results.sbom.json'
      scan-ref: '.'
      github-pat: ${{ inputs.TOKEN_SEC }}


  