name: 'Checkov'
description: 'Execute Checkov' 

runs:  
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v3 

    - name: Install Checkov 
      run: | 
        curl -fsSL https://raw.githubusercontent.com/bridgecrewio/checkov/v1.12.0/install.sh | bash -s
      shell: bash

    - name: 'Run Checkov' 
      run: | 
        checkov -d . --framework terraform 
      shell: bash 
      
    - name: Fail on Errors
      if: ${{ steps.checkov.outputs.exit_code != 0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed(" Checkov found Errors!!!")
          core.setFailed("${{ steps.checkov.outputs.stdout }}")
