name: 'TFSec Scan'
description: 'Execute TFSec' 

runs:  
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v3 

    - name: Install and execute Tfsec
      run: | 
        go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
        tfsec .
      shell: bash
    
    - name: Fail on Errors
      if: ${{ steps.tfsec.outputs.exit_code != 0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('TFsec found Errors!!!') 
